import cmath
a = int(input("enter the number:"))
b = int(input("enter the number:"))
c = int(input("enter the number:"))
d = (b**2) - (4*a*c)
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print("teh roots are")
print(sol1)
print(sol2)
